"""
base_agent.py — Shared infrastructure for all MARGINAL agents.

Provides:
  - Web3 connection to 0G Chain
  - ABI-loaded contract handles
  - 0G Compute client (OpenAI-compatible)
  - 0G Storage helpers (KV + Log)
  - Event subscription utilities
"""
import json
import time
import hashlib
import logging
import asyncio
import aiohttp
from pathlib import Path
from typing import Any, Optional

from web3 import Web3
from web3.middleware import geth_poa_middleware
from eth_account import Account
import openai

from config import Config

logger = logging.getLogger(__name__)

# ── ABI paths (generated by `npx hardhat compile`) ───────────────────────────
ARTIFACTS_DIR = Path(__file__).parent.parent / "artifacts" / "contracts"

def _load_abi(contract_name: str) -> list:
    abi_path = ARTIFACTS_DIR / f"{contract_name}.sol" / f"{contract_name}.json"
    if not abi_path.exists():
        raise FileNotFoundError(
            f"ABI not found at {abi_path}. Run `npm run compile` first."
        )
    with open(abi_path) as f:
        return json.load(f)["abi"]


class BaseAgent:
    """
    Base class for all MARGINAL agents.
    Subclass and override the `run()` coroutine.
    """

    def __init__(self, cfg: Config, role: str):
        self.cfg    = cfg
        self.role   = role
        self.logger = logging.getLogger(f"marginal.{role}")

        # ── Web3 ─────────────────────────────────────────────────────────────
        self.w3 = Web3(Web3.HTTPProvider(cfg.og_rpc_url))
        self.w3.middleware_onion.inject(geth_poa_middleware, layer=0)

        if not self.w3.is_connected():
            self.logger.warning(
                "Could not verify connection to 0G Chain at %s — will retry on first use.",
                cfg.og_rpc_url,
            )

        self.account = Account.from_key(cfg.private_key)
        self.logger.info("Agent wallet: %s", self.account.address)

        # ── Contracts ─────────────────────────────────────────────────────────
        self.auction_house = self.w3.eth.contract(
            address=Web3.to_checksum_address(cfg.auction_house_address),
            abi=_load_abi("AuctionHouse"),
        )
        self.stake_vault = self.w3.eth.contract(
            address=Web3.to_checksum_address(cfg.stake_vault_address),
            abi=_load_abi("StakeVault"),
        )
        self.marginal_nft = self.w3.eth.contract(
            address=Web3.to_checksum_address(cfg.marginal_nft_address),
            abi=_load_abi("MarginalNFT"),
        )

        # ── Inference client (OpenAI-compatible) ──────────────────────────────
        if not cfg.compute_api_key:
            self.logger.warning(
                "OG_COMPUTE_API_KEY is not set. Inference calls will fail. "
                "Set it to your OpenAI / Groq / Together API key in .env."
            )
        self.compute_client = openai.AsyncOpenAI(
            api_key=cfg.compute_api_key or "placeholder",
            base_url=cfg.compute_base_url,
        )

        self.logger.info("%s agent initialised on chain %d", role, cfg.chain_id)

    # ── Transaction helpers ───────────────────────────────────────────────────

    def _build_tx(self, fn, value_wei: int = 0) -> dict:
        """Build a transaction dict ready for signing."""
        nonce = self.w3.eth.get_transaction_count(self.account.address, "pending")
        gas_price = self.w3.eth.gas_price

        tx = fn.build_transaction({
            "from":     self.account.address,
            "nonce":    nonce,
            "gasPrice": gas_price,
            "value":    value_wei,
        })
        # Estimate gas with 20% buffer
        # If estimation fails, the transaction will very likely revert on-chain — do not broadcast
        estimated = self.w3.eth.estimate_gas(tx)
        tx["gas"] = int(estimated * 1.2)

        return tx

    def _send_tx(self, fn, value_wei: int = 0) -> str:
        """Sign and broadcast a transaction. Returns tx hash."""
        tx = self._build_tx(fn, value_wei)
        signed = self.account.sign_transaction(tx)
        tx_hash = self.w3.eth.send_raw_transaction(signed.rawTransaction)
        self.logger.debug("Tx sent: %s", tx_hash.hex())
        receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)
        if receipt.status != 1:
            raise RuntimeError(f"Transaction reverted: {tx_hash.hex()}")
        self.logger.info("Tx confirmed: %s (block %d)", tx_hash.hex(), receipt.blockNumber)
        return tx_hash.hex()

    # ── 0G Compute ───────────────────────────────────────────────────────────

    async def compute_inference(
        self,
        prompt: str,
        system_prompt: str = "You are a precise AI assistant.",
        temperature: float = 0.3,
        max_tokens: int = 1024,
    ) -> tuple[str, int]:
        """
        Call 0G Compute for inference.
        Returns (response_text, tokens_used).
        """
        response = await self.compute_client.chat.completions.create(
            model=self.cfg.compute_model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": prompt},
            ],
            temperature=temperature,
            max_tokens=max_tokens,
        )
        text   = response.choices[0].message.content or ""
        tokens = response.usage.total_tokens if response.usage else len(text.split())
        return text, tokens

    # ── 0G Storage ───────────────────────────────────────────────────────────
    # Primary: 0G Storage node (https://storage.0g.ai or self-hosted)
    # Fallback: Memory Indexer cache at localhost:8001 (always available in local mode)

    _INDEXER_URL = "http://localhost:8001"

    async def storage_kv_write(self, key: str, value: dict) -> bool:
        """Write agent state to 0G Storage KV layer."""
        payload = json.dumps(value)
        url = f"{self.cfg.storage_node_url}/kv/{self.cfg.kv_bucket}/{key}"
        try:
            async with aiohttp.ClientSession() as session:
                async with session.put(
                    url,
                    data=payload,
                    headers={
                        "Content-Type": "application/json",
                        "X-Api-Key": self.cfg.compute_api_key,
                    },
                    timeout=aiohttp.ClientTimeout(total=5),
                ) as resp:
                    if resp.status in (200, 201):
                        return True
        except Exception:
            pass

        # Fallback: write to Memory Indexer storage
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    f"{self._INDEXER_URL}/storage",
                    json={"__kv_key": key, **value},
                    timeout=aiohttp.ClientTimeout(total=5),
                ) as resp:
                    return resp.status == 200
        except Exception as e:
            self.logger.warning("KV write failed (key=%s): %s", key, e)
        return False

    async def storage_kv_read(self, key: str) -> Optional[dict]:
        """Read agent state from 0G Storage KV layer."""
        url = f"{self.cfg.storage_node_url}/kv/{self.cfg.kv_bucket}/{key}"
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(
                    url,
                    headers={"X-Api-Key": self.cfg.compute_api_key},
                    timeout=aiohttp.ClientTimeout(total=5),
                ) as resp:
                    if resp.status == 200:
                        return await resp.json()
        except Exception:
            pass
        return None

    async def storage_log_append(self, entry: dict) -> Optional[str]:
        """
        Append an immutable record to 0G Storage Log layer.
        Returns the log entry pointer (committed on-chain in submitResult).
        Falls back to Memory Indexer when 0G Storage is unreachable.
        """
        payload = json.dumps(entry)
        url = f"{self.cfg.storage_node_url}/log/{self.cfg.log_stream_id}"
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    url,
                    data=payload,
                    headers={
                        "Content-Type": "application/json",
                        "X-Api-Key": self.cfg.compute_api_key,
                    },
                    timeout=aiohttp.ClientTimeout(total=5),
                ) as resp:
                    if resp.status in (200, 201):
                        result = await resp.json()
                        ptr = result.get("id") or result.get("pointer")
                        if ptr:
                            return ptr
        except Exception:
            pass

        # Fallback: Memory Indexer storage (localhost:8001)
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    f"{self._INDEXER_URL}/storage",
                    json=entry,
                    timeout=aiohttp.ClientTimeout(total=5),
                ) as resp:
                    if resp.status == 200:
                        result = await resp.json()
                        self.logger.info(
                            "Stored via Memory Indexer: %s", result.get("pointer")
                        )
                        return result.get("pointer")
        except Exception as e:
            self.logger.warning("Memory Indexer storage write failed: %s", e)

        return None

    async def storage_log_read(self, pointer: str) -> Optional[dict]:
        """Read a log entry by its pointer. Handles both 0G Storage and local pointers."""
        # Memory Indexer storage
        if pointer.startswith("mgidx:"):
            sid = pointer[len("mgidx:"):]
            try:
                async with aiohttp.ClientSession() as session:
                    async with session.get(
                        f"{self._INDEXER_URL}/storage/{sid}",
                        timeout=aiohttp.ClientTimeout(total=5),
                    ) as resp:
                        if resp.status == 200:
                            return await resp.json()
            except Exception as e:
                self.logger.error("Indexer storage read failed (ptr=%s): %s", pointer, e)
            return None

        # 0G Storage node
        url = f"{self.cfg.storage_node_url}/log/{self.cfg.log_stream_id}/{pointer}"
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(
                    url,
                    headers={"X-Api-Key": self.cfg.compute_api_key},
                    timeout=aiohttp.ClientTimeout(total=5),
                ) as resp:
                    if resp.status == 200:
                        return await resp.json()
        except Exception as e:
            self.logger.error("0G Storage read failed (ptr=%s): %s", pointer, e)

        return None

    # ── Utility ───────────────────────────────────────────────────────────────

    @staticmethod
    def compute_output_hash(text: str) -> bytes:
        """Return keccak256 of output text (matches Solidity keccak256)."""
        return Web3.keccak(text=text)

    @staticmethod
    def make_bid_commitment(amount_wei: int, salt: bytes) -> bytes:
        """
        Compute bid commitment = keccak256(abi.encodePacked(amount, salt)).
        Matches the Solidity: keccak256(abi.encodePacked(amount, salt))
        """
        from eth_abi import encode
        packed = encode(["uint256", "bytes32"], [amount_wei, salt])
        return Web3.keccak(packed)

    @staticmethod
    def generate_salt() -> bytes:
        """Generate a cryptographically random 32-byte salt."""
        import secrets
        return secrets.token_bytes(32)

    # ── Main loop ─────────────────────────────────────────────────────────────

    async def run(self):
        """Override in subclass with the agent's main loop."""
        raise NotImplementedError

    def start(self):
        """Synchronous entry point."""
        logging.basicConfig(
            level=logging.INFO,
            format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
        )
        self.logger.info("Starting %s agent (id=%s)...", self.role, self.cfg.agent_id)
        asyncio.run(self.run())
